from aiogram.fsm.state import State, StatesGroup


class AdminStates(StatesGroup):
    waiting_student_name = State()
    waiting_student_username = State()
    waiting_student_phone = State()

    choosing_student_for_lesson = State()
    waiting_teacher_name = State()
    waiting_teacher_selection = State()
    waiting_subject_name = State()
    waiting_tariff_type = State()
    waiting_lesson_balance = State()

    waiting_student_search = State()
    waiting_attendance_student_search = State()
    waiting_balance_student_search = State()
    waiting_history_student_search = State()

    waiting_new_admin_username = State()
    waiting_new_teacher_full_name = State()
    waiting_new_teacher_subject = State()
    waiting_new_teacher_description = State()
    waiting_new_teacher_photo = State()
    waiting_new_teacher_username = State()
    waiting_delete_user_query = State()
    waiting_delete_user_selection = State()
    waiting_bind_teacher_telegram_id = State()
    waiting_role_change_query = State()
    waiting_role_change_selection = State()
    waiting_role_teacher_subject = State()
    waiting_role_teacher_description = State()
    waiting_role_teacher_photo = State()
    waiting_edit_teacher_query = State()
    waiting_edit_teacher_selection = State()
    waiting_edit_teacher_full_name = State()
    waiting_edit_teacher_subject = State()
    waiting_edit_teacher_description = State()
    waiting_edit_teacher_photo = State()
    waiting_edit_teacher_username = State()

    waiting_publication_description = State()
    waiting_publication_photo = State()
    waiting_publication_links = State()
    waiting_publication_audience = State()
    waiting_publication_schedule_mode = State()
    waiting_publication_schedule_datetime = State()
    waiting_payment_chat_message = State()

    waiting_review_description = State()
    waiting_review_media = State()
    waiting_review_links = State()
